---
- name: My Test Playbook
  hosts: localhost
  become: true

  vars:
    mytext: "Hello from Ukraine"
    ans_name_conf: "Name of Python Environment"
    ans_file_conf: "configuration file for creating an environment"
    
  tasks:
  - name: Ping test
    ping:
    register: output
  - debug: 
      var: output
      
  - name: Say Hello to ALL
    debug:
      msg: "Hello {{ item }}"
    loop:
      - Vasya
      - Petya
      - Masha
      - Kolya 

  - name: Create Python Environment
    file:
      path: /home/runner/work/my_task/my_task/{{ ans_name_config }}/
      state: directory
      mode: 0755
  - debug: 
      var: ans_name_config
      
  - name: Create File1
    copy:
      dest: /home/runner/work/my_task/my_task/my_test/file1
      content: |
        Text Line1, in file1
        Text Line2, in file1
        Text Line3, {{ mytext }}
...
