---
- name: My Test Playbook
  hosts: localhost
  become: true

  vars:
    mytext: "Hello from Ukraine"
    ans_name_conf: "Name of Python Environment"
    ans_file_conf: "configuration file for creating an environment"
    
  tasks:
  - name: Ping test
    ping:
    register: output
  - debug: 
      var: output
      
  - name: Check var
    debug: 
      msg: "имя переменной ансибл {{ ans_name_conf }} должно быть req"

  - name: Create Folder of Projekt
    file:
      path: /home/runner/work/my_task/my_task/my_test/test-project-{{ ans_name_conf }}
      state: directory
      mode: 0755
      
  - name: Copy MyHomePage to Servers
    copy:
      src: "/home/runner/work/my_task/my_task/venvs/{{ ans_name_conf }}.txt"
      dest: "/home/runner/work/my_task/my_task/my_test/test-project-{{ ans_name_conf }}"
      mode: 0555 
      
  
  - name: Create Folder2
    file:
      path: /home/runner/work/my_task/my_task/my_test/folder2
      state: directory
      mode: 0755

  - name: Create File1
    copy:
      dest: /home/runner/work/my_task/my_task/my_test/file1
      content: |
        Text Line1, in file1
        Text Line2, in file1
        Text Line3, {{ mytext }}
