---
- name: My Test Playbook
  hosts: localhost
  become: true

  vars:
    ans_name_conf: "Python environment name without extension" 
        
  tasks:
  - name: Ping test
    ping:
    register: output
  - debug: 
      var: output
      
  - name: Install Python
    apt:
      name: python3-pip
      state: present
      update_cache: true
      register: results
  - debug: 
      var: results    
      
  - name: Creating a project folder
    file:
      path: /home/runner/work/my_task/my_task/my_test/test-project-{{ ans_name_conf }}
      state: directory
      mode: 0755
      
  - name: Copying a configuration file to a remote machine
    copy:
      src: "/home/runner/work/my_task/my_task/venvs/{{ ans_name_conf }}.txt" 
      dest: "/home/runner/work/my_task/my_task/my_test/test-project-{{ ans_name_conf }}"
      mode: 0555
      
  - name: Setting the working environment and dependencies
    shell: | 
      cd /home/runner/work/my_task/my_task/my_test/test-project-{{ ans_name_conf }}
      python3 -m venv {{ ans_name_conf }}
      pip install -r {{ ans_name_conf }}.txt  
...
