#------------------------------
# Test GitHub Action
# Sergii Kiskar August 2022
#------------------------------
name: push-control
on: 
  push:
    branches: [ "main" ]

jobs:
  changes:
    runs-on: ubuntu-latest
    steps:
      - id: file_changes
        uses: trilom/file-changes-action@v1.2.3
        with:
          # optional output format
          output: 'json'
          # optional fileoutput format
          # fileOutput: 'csv'
      - name: test
        run: |
          cat $HOME/files.json
          cat $HOME/files_modified.json
          cat $HOME/files_added.json
          echo '${{ steps.file_changes.outputs.files}}'
          echo '${{ steps.file_changes.outputs.files_modified}}'
          echo '${{ steps.file_changes.outputs.files_added}}'
        #  - name: List current Folder
        #  run: |
        #  sed 's/a/b/' $HOME/files_modified.json > $HOME/modi_file1.json
        #  cat $HOME/modi_file1.json
        #  ls -la $HOME/

      - name: test_ansible
        run: |
          cd $HOME/Ansible
          ansible auto -m ping

      - name: Starting Playbook
        env:
          ext: "Ext of file of configuration"
          req_name: "Name of file requirements"
          req_name_config: "file of configuration requirements"
          
        run: |
          sed -e 's/\[//; s/\"//g; s/\]//g' $HOME/files_modified.json > $HOME/file_install_req_mod.json
          Field_Separator=$IFS
          IFS=,
          for val in $(cat $HOME/file_install_req_mod.json);
          do
          echo "$val"
          req_name_config=$(basename $val)
          echo $req_name_config
          req_name=${req_name_config%.*}
          ext=${req_name_config##*.}
          # echo $req_name
          echo $ext
          if [ "$ext" == "txt" ]
          then
          echo "Starting Ansible...."
          else
          echo "This is not configuration file"
          fi
          done
          IFS=$Field_Separator
          ls -la $HOME/
