#------------------------------
# Test GitHub Action
# Sergii Kiskar August 2022
#------------------------------
name: push-control
on: 
  push:
    branches: [ "main" ]

jobs:
  changes:
    runs-on: ubuntu-latest
    steps:
      - id: file_changes
        uses: trilom/file-changes-action@v1.2.3
        with:
          # optional output format
          output: 'json'
          # optional fileoutput format
          # fileOutput: 'csv'
      - name: test
        run: |
          cat $HOME/files.json
          cat $HOME/files_modified.json
          cat $HOME/files_added.json
          echo '${{ steps.file_changes.outputs.files}}'
          echo '${{ steps.file_changes.outputs.files_modified}}'
          echo '${{ steps.file_changes.outputs.files_added}}'
        #  - name: List current Folder
        #  run: |
        #  sed 's/a/b/' $HOME/files_modified.json > $HOME/modi_file1.json
        #  cat $HOME/modi_file1.json
        #  ls -la $HOME/

      - name: test_vor
        run: |
          DataList=" HTML5, CCS3, BootStrap, JQuery "
          Field_Separator=$IFS 
          IFS=.
          for val in $DataList;
          do
          echo $val
          done
          IFS=$Field_Separator

      - name: Starting Playbook
        run: |
          # cat $HOME/files_modified.json
          sed -e 's/\[//; s/\"//g; s/\]//g' $HOME/files_modified.json > $HOME/file_install_req_mod.json
          # cat $HOME/file_install_req_mod.json
          Field_Separator=$IFS
          IFS=,
          for val in $(cat $HOME/file_install_req_mod.json);
          do
          echo "$val"
          req_name_config=$(basename $val)
          echo $req_name_config
          req_name=$(sed -r "s/.+\/(.+)\..+/\1/" $(cat req_name_config)
          echo $req_name
          done
          IFS=$Field_Separator
          ls -la $HOME/
