#------------------------------
# Test GitHub Action
# Sergii Kiskar August 2022
#------------------------------
name: push-control
on: 
  push:
    branches: [ "main" ]
    
jobs:
  changes:
    runs-on: ubuntu-latest
    steps:
      - name: test_vor
        run: |
          DataList=" HTML5, CCS3, BootStrap, JQuery "
          Field_Separator=$IFS 
          IFS=.
          for val in $DataList;
          do
          echo $val
          done
          IFS=$Field_Separator
