#------------------------------
# Test GitHub Action
# Sergii Kiskar August 2022
#------------------------------
name: push-control
on: 
  push:
    branches: [ "main" ]

jobs:
  changes:
    runs-on: ubuntu-latest
    steps:
      - id: file_changes
        uses: trilom/file-changes-action@v1.2.3
        with:
          # optional output format
          output: 'json'
          # optional fileoutput format
          # fileOutput: 'csv'
      - name: test
        run: |
          cat $HOME/files.json
          cat $HOME/files_modified.json
          cat $HOME/files_added.json
          echo '${{ steps.file_changes.outputs.files}}'
          echo '${{ steps.file_changes.outputs.files_modified}}'
          echo '${{ steps.file_changes.outputs.files_added}}'
      - name: List current Folder
        run: |
          sed 's/a/b/' $HOME/files_modified.json > $HOME/modi_file1.json
          cat $HOME/modi_file1.json
          ls -la $HOME/
          
